name: Xamarin

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  
    Android:
      runs-on: macos-latest
      env:
        AppCenterApiToken: ${{ secrets.AppCenterApiToken }}
      steps:
      - uses: actions/checkout@v1
      - name: Android
        run: |
          nuget restore
          msbuild GitTrends.Android/GitTrends.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=AppStore
          
          UITestProject=`find "$HOME" -name GitTrends.UITests.csproj`
          msbuild "$UITestProject" /property:Configuration="Debug"
          
          UITestDLL=`find "$HOME" -name "GitTrends.UITests.dll" | grep bin  | grep -v ref | head -1`
          UITestBuildDir=`dirname $UITestDLL`
          UITestVersionNumber=`grep '[0-9]' $UITestProject | grep Xamarin.UITest|grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
          TestCloudExe=`find ~/.nuget | grep test-cloud.exe | grep $UITestVersionNumber | head -1`
          TestCloudExeDirectory=`dirname $TestCloudExe`
          
          APKFile=`find "$APPCENTER_SOURCE_DIRECTORY" -name *.apk | head -1`
          
          npm install -g appcenter-cli@1.2.2
          appcenter login --token $AppCenterApiToken
          appcenter test run uitest --app "CDA-Global-Beta/GitTrends-Android-Debug" --devices "CDA-Global-Beta/android-os-v5-10" --app-path $APKFile --test-series "master" --locale "en_US" --build-dir $UITestBuildDir --uitest-tools-dir $TestCloudExeDirectory --async
          
    iOS:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: iOS
        run: |
          nuget restore
          msbuild GitTrends.iOS/GitTrends.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhone /p:Configuration=AppStore
